defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  schema_search_path: public
  encoding: utf8
  template: template1

development:
  <<: *defaults
  database: partner_site_development

test:
  <<: *defaults
  database: partner_site_test

production:
  <<: *defaults
  database: partner_site_production